name: CI pipeline for EC2 container server test

on:
  push:
    brancges:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    steps: #job 이름 
      - name: Checkout!!
        uses: actions/checkout@v3 

      - name: Set up Python 3.10!!
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 
  
      - name: Install Dependencies!!
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Dockerhub
        uses: docker/login-actions@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Release to Dockerhub!!
        env:
          NAME: ${{secrets.DOCKERHUB_USERNAME}}
          REPO: djangoimg 
        run: |
          docker build -t $REPO
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO

